# Generated by Django 6.1 on 2026-08-28 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('cloze', 'Cloze'), ('mcq', 'Múltipla escolha')], max_length=16)),
                ('pool', models.CharField(choices=[('review', 'Revisão'), ('exam', 'Simulado')], default='review', max_length=16)),
                ('payload', models.JSONField()),
                ('source', models.CharField(max_length=300)),
                ('comment', models.TextField(blank=True)),
                ('concept_id', models.CharField(blank=True, max_length=200)),
                ('from_weakness', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('intro_window_days', models.PositiveIntegerField(default=30)),
                ('desired_retention', models.FloatField(default=0.9)),
                ('mature_threshold_days', models.PositiveIntegerField(default=21)),
                ('block_size', models.PositiveIntegerField(default=15)),
                ('blocks_per_session', models.PositiveIntegerField(default=3)),
                ('player_hp', models.PositiveIntegerField(default=5)),
                ('fast_answer_seconds', models.FloatField(default=20.0)),
                ('boss_unlock_ratio', models.FloatField(default=0.7)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('review_only_days', models.PositiveIntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsrs_state', models.JSONField(default=dict)),
                ('due', models.DateTimeField(db_index=True)),
                ('stability', models.FloatField(db_index=True, default=0.0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('introduced_at', models.DateTimeField(auto_now_add=True)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pack'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('hp_remaining', models.IntegerField(default=0)),
                ('is_boss', models.BooleanField(default=False)),
                ('outcome', models.CharField(default='ongoing', max_length=16)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.pack')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('elapsed_ms', models.PositiveIntegerField()),
                ('was_correct', models.BooleanField(null=True)),
                ('was_guess', models.BooleanField(default=False)),
                ('was_new', models.BooleanField(default=False)),
                ('stability_before', models.FloatField(default=0.0)),
                ('stability_after', models.FloatField(default=0.0)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.card')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.session')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(db_index=True, max_length=200)),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.pack')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.topic')),
                ('unlocks', models.ManyToManyField(blank=True, related_name='unlocked_by', to='core.topic')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='boss_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_runs', to='core.topic'),
        ),
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.topic'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['player', 'due'], name='core_card_player__983acd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('player', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('pack', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('pack', 'external_id')},
        ),
    ]
