# Generated by Django 6.1 on 2026-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cards_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='cards_in_block',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='damage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='session',
            name='enemies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='enemy_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
